on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: 'true'
      - run: dotnet restore --locked-mode
      - run: dotnet build --no-restore --configuration Debug
      - run: dotnet test --no-build --verbosity normal